//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// ImageTool.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ImageToolTYPE               130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_OUTPUTWND               149
#define IDS_OUTPUT_WND                  157
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_OUTPUT_POPUP                182
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   306
#define IDD_FILE_NEW                    310
#define IDD_BRIGHTNESS_CONTRAST         311
#define IDD_GAMMA_CORRECTION            312
#define IDD_HISTOGRAM                   313
#define IDD_ARITHMETIC_LOGICAL          314
#define IDD_GAUSSIAN                    315
#define IDD_ADD_NOISE                   316
#define IDD_DIFFUSION                   317
#define IDD_TRANSLATE                   318
#define IDD_RESIZE                      319
#define IDD_ROTATE                      320
#define IDD_FREQUENCY_FILTERING         321
#define IDD_CANNY_EDGE                  322
#define IDD_HARRIS_CORNER               323
#define IDD_COLOR_COMBINE               324
#define IDD_BINARIZATION                325
#define IDD_FOURIER_DESCRIPTOR          326
#define IDC_WIDTH                       1000
#define IDC_HEIGHT                      1001
#define IDC_IMAGE_TYPE                  1002
#define IDC_BRIGHTNESS_SLIDER           1003
#define IDC_BRIGHTNESS_EDIT             1004
#define IDC_CONTRAST_SLIDER             1005
#define IDC_CONTRAST_EDIT               1006
#define IDC_GAMMA_SLIDER                1007
#define IDC_GAMMA_EDIT                  1008
#define IDC_COMBO_IMAGE1                1009
#define IDC_COMBO_IMAGE2                1010
#define IDC_FUNCTION1                   1011
#define IDC_FUNCTION2                   1012
#define IDC_FUNCTION3                   1013
#define IDC_FUNCTION4                   1014
#define IDC_FUNCTION5                   1015
#define IDC_FUNCTION6                   1016
#define IDC_SIGMA_SLIDER                1017
#define IDC_SIGMA_EDIT                  1018
#define IDC_NOISE_RADIO1                1019
#define IDC_NOISE_RADIO2                1020
#define IDC_NOISE_AMOUNT                1021
#define IDC_SPIN_AMOUNT                 1022
#define IDC_DIFFUSION_LAMBDA            1023
#define IDC_DIFFUSION_K                 1024
#define IDC_DIFFUSION_ITER              1025
#define IDC_NEW_SX                      1026
#define IDC_NEW_SY                      1027
#define IDC_OLD_WIDTH                   1028
#define IDC_NEW_WIDTH                   1029
#define IDC_SPIN_WIDTH                  1030
#define IDC_OLD_HEIGHT                  1031
#define IDC_NEW_HEIGHT                  1032
#define IDC_SPIN_HEIGHT                 1033
#define IDC_ASPECT_RATIO                1034
#define IDC_INTERPOLATION               1035
#define IDC_ROTATE1                     1036
#define IDC_ROTATE2                     1037
#define IDC_ROTATE3                     1038
#define IDC_ROTATE4                     1039
#define IDC_ANGLE                       1040
#define IDC_FILTER_TYPE                 1041
#define IDC_FILTER_SHAPE                1042
#define IDC_CUTOFF_FREQ                 1043
#define IDC_CUTOFF_RANGE                1044
#define IDC_CANNY_SIGMA                 1045
#define IDC_LOW_THRESHOLD               1046
#define IDC_HIGH_THRESHOLD              1047
#define IDC_HARRIS_THRESHOLD            1048
#define IDC_COLOR_SPACE                 1049
#define IDC_COMBO_IMAGE3                1050
#define IDC_IMAGE_PREVIEW               1051
#define IDC_THRESHOLD_SLIDER            1052
#define IDC_THRESHOLD_EDIT              1053
#define IDC_PERCENT                     1054
#define ID_WINDOW_DUPLICATE             32771
#define ID_VIEW_ZOOM1                   32772
#define ID_VIEW_ZOOM2                   32773
#define ID_VIEW_ZOOM3                   32774
#define ID_VIEW_ZOOM4                   32775
#define ID_IMAGE_INVERSE                32776
#define ID_BRIGHTNESS_CONTRAST          32777
#define ID_GAMMA_CORRECTION             32778
#define ID_VIEW_HISTOGRAM               32779
#define ID_HISTO_STRETCHING             32780
#define ID_HISTO_EQUALIZATION           32781
#define ID_ARITHMETIC_LOGICAL           32782
#define ID_BITPLANE_SLICING             32783
#define ID_WINDOW_CLOSEALL              32784
#define ID_FILTER_MEAN                  32785
#define ID_FILTER_WEIGHTED_MEAN         32786
#define ID_FILTER_GAUSSIAN              32787
#define ID_FILTER_LAPLACIAN             32788
#define ID_FILTER_UNSHARP_MASK          32789
#define ID_FILTER_HIGHBOOST             32790
#define ID_ADD_NOISE                    32791
#define ID_FILTER_MEDIAN                32792
#define ID_FILTER_DIFFUSION             32793
#define ID_IMAGE_TRANSLATION            32794
#define ID_IMAGE_RESIZE                 32795
#define ID_IMAGE_ROTATE                 32796
#define ID_IMAGE_MIRROR                 32797
#define ID_IMAGE_FLIP                   32798
#define ID_FOURIER_DFT                  32799
#define ID_FOURIER_DFTRC                32800
#define ID_FOURIER_FFT                  32801
#define ID_FREQ_FILTERING               32802
#define ID_EDGE_ROBERTS                 32803
#define ID_EDGE_PREWITT                 32804
#define ID_EDGE_SOBEL                   32805
#define ID_EDGE_CANNY                   32806
#define ID_HOUGH_LINE                   32807
#define ID_HARRIS_CORNER                32808
#define ID_COLOR_GRAYSCALE              32809
#define ID_COLOR_SPLIT_RGB              32810
#define ID_COLOR_SPLIT_HSI              32811
#define ID_COLOR_SPLIT_YUV              32812
#define ID_COLOR_COMBINE_RGB            32813
#define ID_COLOR_COMBINE_HSI            32814
#define ID_COLOR_COMBINE_YUV            32815
#define ID_COLOR_EDGE                   32816
#define ID_SEGMENT_BINARIZATION         32817
#define ID_SEGMENT_LABELING             32818
#define ID_CONTOUR_TRACING              32819
#define ID_MORPHOLOGY_EROSION           32820
#define ID_MORPHOLOGY_DILATION          32821
#define ID_MORPHOLOGY_OPENING           32822
#define ID_MORPHOLOGY_CLOSING           32823
#define ID_GRAYMORPH_EROSION            32824
#define ID_GRAYMORPH_DILATION           32825
#define ID_GRAYMORPH_OPENING            32826
#define ID_GRAYMORPH_CLOSING            32827
#define ID_FOURIER_DESCRIPTOR           32828
#define ID_INVARIANT_MOMENTS            32829
#define ID_ZERNIKE_MOMENTS              32830
#define ID_TEMPLATE_MATCHING            32831

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        327
#define _APS_NEXT_COMMAND_VALUE         32832
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
